### ISSUE TITLE
About how to write my own Virtual Font for LuaLaTeX-ja

### ISSUE THREAD

**Issue by Steve-Cheung-emct** [abenori/jlreq#63]
Mr. Abenori

I've written many ZVP/VF(s) for tate Chinese text in UpTeX.

But I am confuse on how to modify the tate virtual font for lualatex-ja. 

I know nothing about it, where did thus VF(s) for Luatex saved in my computer, and how to change the position of punctuation characters in tate mode, for ex. to rise up or get down the location of the Char in VF.

And more, I am intesting in CID in Lualatex-la, please help me if possible, Thank you very much.

Steve Cheung

**Comment by Steve-Cheung-emct** [comment]
![页面提取自－main](https://user-images.githubusercontent.com/26833892/79072718-1945a000-7d15-11ea-89c6-87ce79449c64.png)

**Comment by abenori** [comment]
You can change the position of some characters using JFM of LuaTeX-ja. The following might be helpful for you.
https://github.com/abenori/jlreq/issues/33#issuecomment-572083349

A package `luatexja-otf` is distributed with LuaTeX-ja package and you can use `\CID` command with the package. Please see 3.4 of the LuaTeX-ja manual. Here is an example (from the manual).

```
\documentclass[lualatex]{jlreq}
\usepackage{luatexja-otf}
\begin{document}
\CID{7652}飾区の\CID{13706}野家．
\end{document}
```

(Does the answer work?)

Because these are not specialized to `jlreq` class file but more general things with LuaTeX-ja package, I recommend to post questions to [LuaTeX-ja forum](https://ja.osdn.net/projects/luatex-ja/). More people (including me) is looking there.

**Comment by Steve-Cheung-emct** [comment]
Thank you for your advise.

The structure of jfm-jlreqv.lua is so complex to be understood or modified. I would try more and more times.   :)

By the way, I was to make a continuous gap between two underlines or waves, with a package named as uline--.sty by T. Yoshinaga(吉永 徹美氏). When I produce two underlines in ancient books typed by uptex. for example. 

The lines would be continuous without a gap betwwen two underlines (when there is no gap between Kanji).

```
\uline{唐}\uline{李太白}

\oline{唐}\oline{白居易}

\owave{宋}\owave{蘇東坡}
```

![0002](https://user-images.githubusercontent.com/26833892/79241329-838d4a80-7ea5-11ea-90cb-91ceb4abb318.png)

I am very puzzle, thank you for your response.

SC

**Comment by abenori** [comment]
Did you try to modify jfm-jlreqv.lua directly? It's impossible. You should modify jfm-jlreq.lua and produce jfm-jlreqv.lua by running make_variant_jfm.lua.

For `\uline`, I have no good idea. One way might be the following:
```
\kern 1pt\uline{\hbox{\kern -1pt唐\kern -1pt}}\kern 2pt\uline{\hbox{\kern -1pt 李}太\hbox{白\kern -1pt}}\kern 1pt
```
Then each underline becomes 1pt shorter.

**Comment by Steve-Cheung-emct** [comment]
Thank you very much.

感謝！
